- name: update all servers
  hosts: all
  become: yes

  tasks:
   - name: update apt
     apt:
       update_cache: yes

   - name: insatll apache
     package:
       name: apache2
       state: present 

   - name: start apache2
     service:
       name: apache2
       state: started

   - name: enable apache2
     service:
       name: apache2
       enabled: yes  

